# Use a lightweight Node.js image
FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY backend/package.json package-lock.json ./
COPY backend/ . 
RUN npm install

# # Copy the rest of the application
# COPY . .

# Expose API port
EXPOSE 8080

# Run the backend API
CMD ["npm", "start"]
